version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    hostname: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=bodleiandiff
      # Disable to run on Docker for Mac for Kubernetes
      - bootstrap.memory_lock=true
      #- xpack.security.enabled=false
      #- xpack.monitoring.enabled=false
      #- xpack.ml.enabled=false
      #- xpack.graph.enabled=false
      #- xpack.watcher.enabled=false
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.4
    hostname: kibana
    volumes:
      - ./etc/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
